from utils import helpers as help

# Main backgrounds
MAIN_BACKGROUND = "#121416"
HEADER_BACKGROUND = "#1B1E21"
SIDEBAR_BACKGROUND = "#1B1E21"
CARD_BACKGROUND = "#272B2F"
CARD_HOVER = "#34393E"

# Borders and dividers
BORDER_COLOR = "#464C52"
DIVIDER_COLOR = "#34393E"

# Accent colors
PRIMARY_YELLOW = "#FFD42A"
PRIMARY_YELLOW_HOVER = "#E6BE20"
PRIMARY_YELLOW_DISABLED = "#8A741B"

# Text colors
TEXT_PRIMARY = "#F2F2F2"
TEXT_SECONDARY = "#A8ADB2"
TEXT_DISABLED = "#686D72"
TEXT_ON_YELLOW = "#121416"

# Status colors
SUCCESS_COLOR = "#4CAF70"
ERROR_COLOR = "#E05252"
WARNING_COLOR = "#FFD42A"

# Input colors
INPUT_BACKGROUND = "#202428"
INPUT_BORDER = "#464C52"
INPUT_FOCUS_BORDER = "#FFD42A"

# Button colors
PRIMARY_BUTTON = "#FFD42A"
PRIMARY_BUTTON_HOVER = "#E6BE20"
PRIMARY_BUTTON_TEXT = "#121416"

SECONDARY_BUTTON = "#34393E"
SECONDARY_BUTTON_HOVER = "#464C52"
SECONDARY_BUTTON_TEXT = "#F2F2F2"

DANGER_BUTTON = "#E05252"
DANGER_BUTTON_HOVER = "#C74444"
DANGER_BUTTON_TEXT = "#F2F2F2"

# Widget settings
CORNER_RADIUS = 6
CARD_CORNER_RADIUS = 6
BUTTON_CORNER_RADIUS = 4
BORDER_WIDTH = 1

# Images
APP_ICON = help.resource_path("assets/ducktape_dock.ico")
APP_LOGO = help.resource_path("assets/ducktape_dock.png")